config/routes.rb
PermissionManager::Application.routes.draw do
  get "codes" => 'codes#index'
  get "codes/setup/username" => 'codes#setup_username'
  post "codes/setup/repositories" => 'codes#setup_repositories'
  root 'tasks#index'
  get "login/index"
  post "login/login"
  get "login/logout"

  resources :tasks

  resources :permissions

  resources :roles
  post "/roles/assign_permissions"
  post "/roles/permissions" => 'roles#permissions'

  resources :users
  post "/users/assign_roles" => 'users#assign_roles'

  resources :accounts

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  account_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Task < ActiveRecord::Base
    belongs_to :account

    validates :content, :account_id, presence: true
    validates :content, length: { maximum: 255 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  authorize_resource :task
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.where 'account_id = ?', current_user.id
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    @task.account_id = current_user.id
    if @task.save
      redirect_to @task, notice: '任务已成功创建。'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: '任务已成功更新。'
    else
      render action: 'edit'
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content,'内容' %><br>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit '提交', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>编辑任务</h1>

<%= render 'form' %>

<%= link_to '返回', tasks_path %>

app/views/tasks/index.html.erb
<% if flash[:info] %>
<div class="alert alert-success alert-dismissable"><%= flash[:info] %></div>
<% end %>
<h1>任务列表</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>内容</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td></td>
        <td><%= link_to '编辑', edit_task_path(task) %></td>
        <td>
          <%= link_to '删除', task, method: :delete, data: { confirm: '你确定要删除吗？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建任务', new_task_path %>

app/views/tasks/new.html.erb
<h1>新建任务</h1>

<%= render 'form' %>

<%= link_to '返回', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice" ><%= notice %></p>

<p>
  <strong>内容:</strong>
  <%= @task.content %>
</p>

<%= link_to '编辑', edit_task_path(@task) %> |
<%= link_to '返回', tasks_path %>