config/routes.rb
PermissionManager::Application.routes.draw do
  get "codes" => 'codes#index'
  get "codes/setup/username" => 'codes#setup_username'
  post "codes/setup/repositories" => 'codes#setup_repositories'
  root 'tasks#index'
  get "login/index"
  post "login/login"
  get "login/logout"

  resources :tasks

  resources :permissions

  resources :roles
  post "/roles/assign_permissions"
  post "/roles/permissions" => 'roles#permissions'

  resources :users
  post "/users/assign_roles" => 'users#assign_roles'

  resources :accounts

end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Role < ActiveRecord::Base
	has_many :role_permissions
	has_many :permissions, :through => :role_permissions

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  authorize_resource :role
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
    @permissions = Permission.all
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: '角色已成功创建。'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: '角色已成功更新。'
    else
      render action: 'edit'
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url
  end

  def assign_permissions
    role_id = params[:role_id]
    RolePermission.transaction do
      news = params[:news].split(',')
      news.each do |n|
        RolePermission.create!(role_id: role_id, permission_id: n)
      end
      deleteds = params[:deleteds].split(',')
      deleteds.each do |d|
        RolePermission.destroy_all ['role_id = ? and permission_id = ?', role_id, d]
      end
    end
    render json: { success: true, message: '权限分配成功' }
  rescue Exception => e
    render json: { success: false, message: '权限分配失败' }
  end

  def permissions
    ids = params[:ids].split(",")
    roles = Role.find(ids)
    permissions = []
    roles.each do |role|
      permissions.concat role.permissions
    end
    render json: { success: true, permissions: permissions }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
    def role_has_permission(permission)
        @role.permissions.each do |p|
            return "checked" if permission.id == p.id
        end
        ""
    end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '角色名' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit '提交', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>编辑角色</h1>

<%= render 'form' %>

<%= link_to '查看', @role %> |
<%= link_to '返回', roles_path %>

app/views/roles/index.html.erb
<h1>用户角色</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>角色名</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to '查看', role %></td>
        <td><%= link_to '编辑', edit_role_path(role) %></td>
        <td><%= link_to '删除', role, method: :delete, data: { confirm: '你确定吗？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建角色', new_role_path %>

app/views/roles/new.html.erb
<h1>新建角色</h1>

<%= render 'form' %>

<%= link_to '返回', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p class="h1">
    <%= @role.name %> 拥有的权限
</p>

<table class="table">
  <thead>
    <tr>
      <th>描述</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.description %></td>
        <td>
          <input name="assign_role" type="checkbox" <%= role_has_permission(permission) %> permission_id="<%= permission.id %>"/>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<input id="btnAssignPermission" type="button" value="提交更改" class="btn btn-default" role_id="<%= @role.id %>"/>
<br /><br />
<%= link_to '编辑', edit_role_path(@role) %> |
<%= link_to '返回', roles_path %>